import Head from "next/head";
import { Header } from "../components/Header/index.jsx";

import { useBgLightBlue } from "../hooks/usebglightblue";
import { Layout } from "../components/Layout/index";
import "tailwindcss/tailwind.css";
import { SWRConfig } from "swr";

const fetcher = async (...args) => {
  const res = await fetch(...args);
  return await res.json();
};

const MyApp = ({ Component, pageProps }) => {
  useBgLightBlue();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SWRConfig value={{ fetcher }}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </SWRConfig>
    </div>
  );
};

export default MyApp;
