import "../styles/globals.css";
import Head from "next/head";
import { useCounter } from "../hooks/useCounter";
import { useInputarray } from "../hooks/useInputarray";
import { useBgLightBlue } from "../hooks/useBglightBlue";
import { Layout } from "../components/Layout/index";

const MyApp = ({ Component, pageProps }) => {
  const counter = useCounter();
  const inputArray = useInputarray();
  useBgLightBlue();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component foo={123} {...pageProps} {...counter} {...inputArray} />
      </Layout>
    </div>
  );
};

export default MyApp;
